"""Applications, their frozen snapshots and status history (T-016, master flow §4.8–4.9).

- One application per candidate (CNIC) per job, enforced by a unique constraint.
- Submitted applications are final: no edit or withdraw.
- application_no (e.g. PR-2026-000123) is generated by the database from a sequence.
"""

from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    Sequence,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from app.models.base import enum_type
from app.models.enums import ApplicationStatus, FeeStatus

application_no_seq = Sequence("application_no_seq", metadata=db.metadata)

APPLICATION_NO_DEFAULT = text(
    "'PR-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('application_no_seq')::text, 6, '0')"
)

snapshot_documents = Table(
    "snapshot_documents",
    db.metadata,
    Column(
        "snapshot_id", ForeignKey("application_snapshots.id", ondelete="CASCADE"), primary_key=True
    ),
    Column("document_id", ForeignKey("documents.id"), primary_key=True),
)


class Application(db.Model):
    __tablename__ = "applications"
    __table_args__ = (UniqueConstraint("profile_id", "job_id"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    application_no: Mapped[str] = mapped_column(
        String(20), unique=True, nullable=False, server_default=APPLICATION_NO_DEFAULT
    )
    profile_id: Mapped[int] = mapped_column(
        ForeignKey("candidate_profiles.id"), index=True, nullable=False
    )
    job_id: Mapped[int] = mapped_column(ForeignKey("jobs.id"), index=True, nullable=False)
    status: Mapped[ApplicationStatus] = mapped_column(
        enum_type(ApplicationStatus, "application_status"),
        default=ApplicationStatus.SUBMITTED,
        nullable=False,
        index=True,
    )
    submitted_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Fee (T-063): the job's fee at submission, paid by bank challan and confirmed by staff.
    fee_amount: Mapped[Decimal] = mapped_column(
        Numeric(10, 2), server_default=text("0"), nullable=False
    )
    fee_status: Mapped[FeeStatus] = mapped_column(
        enum_type(FeeStatus, "fee_status"),
        default=FeeStatus.NOT_REQUIRED,
        server_default=FeeStatus.NOT_REQUIRED.value,
        nullable=False,
    )
    fee_paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Bank transaction / stamped challan number recorded by the staff member who confirmed it.
    fee_reference: Mapped[str | None] = mapped_column(String(60))
    fee_confirmed_by_id: Mapped[int | None] = mapped_column(ForeignKey("staff_users.id"))

    profile = relationship("CandidateProfile")
    job = relationship("Job")
    snapshot: Mapped["ApplicationSnapshot"] = relationship(
        back_populates="application", uselist=False, cascade="all, delete-orphan"
    )
    events: Mapped[list["StatusEvent"]] = relationship(
        back_populates="application", order_by="StatusEvent.created_at"
    )


class ApplicationSnapshot(db.Model):
    """Profile data frozen at submission; later profile edits never change it."""

    __tablename__ = "application_snapshots"

    id: Mapped[int] = mapped_column(primary_key=True)
    application_id: Mapped[int] = mapped_column(
        ForeignKey("applications.id", ondelete="CASCADE"), unique=True, nullable=False
    )
    profile_data: Mapped[dict] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    application: Mapped[Application] = relationship(back_populates="snapshot")
    documents = relationship("Document", secondary=snapshot_documents)


class StatusEvent(db.Model):
    """Every application status change. Drives tracking and (later) notifications."""

    __tablename__ = "status_events"
    __table_args__ = (
        Index("ix_status_events_application_created", "application_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    application_id: Mapped[int] = mapped_column(
        ForeignKey("applications.id", ondelete="CASCADE"), nullable=False
    )
    status: Mapped[ApplicationStatus] = mapped_column(
        enum_type(ApplicationStatus, "status_event_status"), nullable=False
    )
    note: Mapped[str | None] = mapped_column(Text)
    actor_staff_id: Mapped[int | None] = mapped_column(ForeignKey("staff_users.id"))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    application: Mapped[Application] = relationship(back_populates="events")
