"""admin panel: draft requisitions and settings

Revision ID: 421b3b03655d
Revises: e3f45ae9f155
Create Date: 2026-09-26 02:40:47.816941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '421b3b03655d'
down_revision = 'e3f45ae9f155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['staff_users.id'], name=op.f('fk_settings_updated_by_id_staff_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requisition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('opening_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('closing_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('closing_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('opening_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('requisition')

    op.drop_table('settings')
    # ### end Alembic commands ###
