"""T-010 initial data model

Revision ID: 49eef685e076
Revises: 
Create Date: 2026-09-24 14:32:46.120465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49eef685e076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Added by hand: autogenerate doesn't detect sequences. Feeds applications.application_no.
    op.execute(sa.schema.CreateSequence(sa.Sequence('application_no_seq')))
    op.create_table('candidate_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cnic ~ '^\\d{5}-\\d{7}-\\d$'", name=op.f('ck_candidate_accounts_cnic_format')),
    sa.CheckConstraint("mobile ~ '^03\\d{9}$'", name=op.f('ck_candidate_accounts_mobile_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_accounts')),
    sa.UniqueConstraint('cnic', name=op.f('uq_candidate_accounts_cnic'))
    )
    op.create_table('departments',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_departments'))
    )
    op.create_table('document_types',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_document_types'))
    )
    op.create_table('provinces',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_provinces'))
    )
    op.create_table('qualification_levels',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_qualification_levels'))
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], name=op.f('fk_districts_province_code_provinces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('province_code', 'name', name=op.f('uq_districts_province_code_name'))
    )
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('job_creator', 'approver', 'admin', name='staff_role', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('department_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], name=op.f('fk_staff_users_department_code_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users')),
    sa.UniqueConstraint('email', name=op.f('uq_staff_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=False),
    sa.Column('actor_staff_id', sa.Integer(), nullable=True),
    sa.Column('actor_candidate_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_candidate_id'], ['candidate_accounts.id'], name=op.f('fk_audit_logs_actor_candidate_id_candidate_accounts')),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff_users.id'], name=op.f('fk_audit_logs_actor_staff_id_staff_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('father_name', sa.String(length=120), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'transgender', name='gender', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('domicile_province_code', sa.String(length=10), nullable=True),
    sa.Column('domicile_district_id', sa.Integer(), nullable=True),
    sa.Column('is_government_employee', sa.Boolean(), nullable=False),
    sa.Column('has_disability', sa.Boolean(), nullable=False),
    sa.Column('is_minority', sa.Boolean(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String(length=120)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('statement_of_purpose', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['candidate_accounts.id'], name=op.f('fk_candidate_profiles_account_id_candidate_accounts')),
    sa.ForeignKeyConstraint(['domicile_district_id'], ['districts.id'], name=op.f('fk_candidate_profiles_domicile_district_id_districts')),
    sa.ForeignKeyConstraint(['domicile_province_code'], ['provinces.code'], name=op.f('fk_candidate_profiles_domicile_province_code_provinces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles')),
    sa.UniqueConstraint('account_id', name=op.f('uq_candidate_profiles_account_id'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('department_code', sa.String(length=10), nullable=False),
    sa.Column('bps', sa.SmallInteger(), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('employment_type', sa.Enum('permanent', 'contract', name='employment_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'returned', 'rejected', 'approved', 'published', 'closed', name='job_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('requisition_ref', sa.String(length=60), nullable=True),
    sa.Column('advertisement_no', sa.String(length=40), nullable=True),
    sa.Column('opening_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closing_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('age_cutoff_date', sa.Date(), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bps BETWEEN 1 AND 22', name=op.f('ck_jobs_bps_range')),
    sa.CheckConstraint('closing_date > opening_date', name=op.f('ck_jobs_closing_after_opening')),
    sa.CheckConstraint('fee_amount >= 0', name=op.f('ck_jobs_fee_not_negative')),
    sa.CheckConstraint('vacancies > 0', name=op.f('ck_jobs_vacancies_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], name=op.f('fk_jobs_created_by_id_staff_users')),
    sa.ForeignKeyConstraint(['department_code'], ['departments.code'], name=op.f('fk_jobs_department_code_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('advertisement_no', name=op.f('uq_jobs_advertisement_no'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_no', sa.String(length=20), server_default=sa.text("'PR-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('application_no_seq')::text, 6, '0')"), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'rejected', 'shortlisted', 'admit_card_issued', 'test_interview', 'result', 'merit_list', 'document_verification', 'medical', 'offer', name='application_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_applications_profile_id_candidate_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('application_no', name=op.f('uq_applications_application_no')),
    sa.UniqueConstraint('profile_id', 'job_id', name=op.f('uq_applications_profile_id_job_id'))
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_status'), ['status'], unique=False)

    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('approved', 'returned', 'rejected', name='approval_action', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['staff_users.id'], name=op.f('fk_approval_records_approver_id_staff_users')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_approval_records_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_records_job_id'), ['job_id'], unique=False)

    op.create_table('candidate_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('organization', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_candidate_references_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_references'))
    )
    with op.batch_alter_table('candidate_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_references_profile_id'), ['profile_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_types.code'], name=op.f('fk_documents_document_type_code_document_types')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_documents_profile_id_candidate_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('uq_documents_current_type', ['profile_id', 'document_type_code'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))

    op.create_table('job_domicile_provinces',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('province_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_domicile_provinces_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], name=op.f('fk_job_domicile_provinces_province_code_provinces')),
    sa.PrimaryKeyConstraint('job_id', 'province_code', name=op.f('pk_job_domicile_provinces'))
    )
    op.create_table('job_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('open_merit', 'provincial', 'women', 'minority', 'disability', name='quota_category', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.CheckConstraint('seats > 0', name=op.f('ck_job_quotas_seats_positive')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_quotas_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_quotas')),
    sa.UniqueConstraint('job_id', 'category', name=op.f('uq_job_quotas_job_id_category'))
    )
    op.create_table('job_required_documents',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('document_type_code', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_type_code'], ['document_types.code'], name=op.f('fk_job_required_documents_document_type_code_document_types')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_required_documents_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'document_type_code', name=op.f('pk_job_required_documents'))
    )
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('min_qualification_code', sa.String(length=20), nullable=False),
    sa.Column('accepted_disciplines', sa.ARRAY(sa.String(length=120)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('min_marks_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_experience_years', sa.Numeric(precision=4, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('age_min', sa.SmallInteger(), nullable=False),
    sa.Column('age_max', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('age_min > 0 AND age_max >= age_min', name=op.f('ck_job_requirements_age_range_valid')),
    sa.CheckConstraint('min_experience_years >= 0', name=op.f('ck_job_requirements_experience_not_negative')),
    sa.CheckConstraint('min_marks_percent BETWEEN 0 AND 100', name=op.f('ck_job_requirements_min_marks_range')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_requirements_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['min_qualification_code'], ['qualification_levels.code'], name=op.f('fk_job_requirements_min_qualification_code_qualification_levels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirements')),
    sa.UniqueConstraint('job_id', name=op.f('uq_job_requirements_job_id'))
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_publications_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publications'))
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_profile_id'), ['profile_id'], unique=False)

    op.create_table('application_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_snapshots_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_snapshots')),
    sa.UniqueConstraint('application_id', name=op.f('uq_application_snapshots_application_id'))
    )
    op.create_table('education_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('qualification_level_code', sa.String(length=20), nullable=False),
    sa.Column('discipline', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=160), nullable=False),
    sa.Column('passing_year', sa.SmallInteger(), nullable=False),
    sa.Column('marks_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('certificate_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('marks_percent BETWEEN 0 AND 100', name=op.f('ck_education_records_marks_percent_range')),
    sa.CheckConstraint('passing_year BETWEEN 1950 AND 2100', name=op.f('ck_education_records_passing_year_range')),
    sa.ForeignKeyConstraint(['certificate_document_id'], ['documents.id'], name=op.f('fk_education_records_certificate_document_id_documents')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_education_records_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_level_code'], ['qualification_levels.code'], name=op.f('fk_education_records_qualification_level_code_qualification_levels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education_records'))
    )
    with op.batch_alter_table('education_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_records_profile_id'), ['profile_id'], unique=False)

    op.create_table('experience_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('certificate_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_current AND end_date IS NULL) OR (NOT is_current AND end_date IS NOT NULL AND end_date >= start_date)', name=op.f('ck_experience_records_dates_consistent')),
    sa.ForeignKeyConstraint(['certificate_document_id'], ['documents.id'], name=op.f('fk_experience_records_certificate_document_id_documents')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_experience_records_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience_records'))
    )
    with op.batch_alter_table('experience_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experience_records_profile_id'), ['profile_id'], unique=False)

    op.create_table('professional_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=120), nullable=False),
    sa.Column('registration_no', sa.String(length=60), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_professional_registrations_document_id_documents')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_professional_registrations_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_registrations'))
    )
    with op.batch_alter_table('professional_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professional_registrations_profile_id'), ['profile_id'], unique=False)

    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'under_review', 'rejected', 'shortlisted', 'admit_card_issued', 'test_interview', 'result', 'merit_list', 'document_verification', 'medical', 'offer', name='status_event_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_staff_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff_users.id'], name=op.f('fk_status_events_actor_staff_id_staff_users')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_status_events_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_events'))
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index('ix_status_events_application_created', ['application_id', 'created_at'], unique=False)

    op.create_table('snapshot_documents',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_snapshot_documents_document_id_documents')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['application_snapshots.id'], name=op.f('fk_snapshot_documents_snapshot_id_application_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'document_id', name=op.f('pk_snapshot_documents'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot_documents')
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index('ix_status_events_application_created')

    op.drop_table('status_events')
    with op.batch_alter_table('professional_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professional_registrations_profile_id'))

    op.drop_table('professional_registrations')
    with op.batch_alter_table('experience_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experience_records_profile_id'))

    op.drop_table('experience_records')
    with op.batch_alter_table('education_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_education_records_profile_id'))

    op.drop_table('education_records')
    op.drop_table('application_snapshots')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_profile_id'))

    op.drop_table('publications')
    op.drop_table('job_requirements')
    op.drop_table('job_required_documents')
    op.drop_table('job_quotas')
    op.drop_table('job_domicile_provinces')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('uq_documents_current_type', postgresql_where=sa.text('archived_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_documents_profile_id'))

    op.drop_table('documents')
    with op.batch_alter_table('candidate_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_references_profile_id'))

    op.drop_table('candidate_references')
    with op.batch_alter_table('approval_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_records_job_id'))

    op.drop_table('approval_records')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_status'))
        batch_op.drop_index(batch_op.f('ix_applications_profile_id'))
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))

    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    op.drop_table('candidate_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')

    op.drop_table('audit_logs')
    op.drop_table('staff_users')
    op.drop_table('districts')
    op.drop_table('qualification_levels')
    op.drop_table('provinces')
    op.drop_table('document_types')
    op.drop_table('departments')
    op.drop_table('candidate_accounts')
    op.execute(sa.schema.DropSequence(sa.Sequence('application_no_seq')))
    # ### end Alembic commands ###
