"""T-021 otp challenges and revoked tokens

Revision ID: 4a947c997756
Revises: 49eef685e076
Create Date: 2026-09-25 12:28:21.379463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a947c997756'
down_revision = '49eef685e076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('signup', 'login', name='otp_purpose', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_otp_challenges_attempts_not_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_challenges_cnic'), ['cnic'], unique=False)
        batch_op.create_index(batch_op.f('ix_otp_challenges_mobile'), ['mobile'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_revoked_tokens'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_challenges_mobile'))
        batch_op.drop_index(batch_op.f('ix_otp_challenges_cnic'))

    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
