"""T-149 profile claims and highest qualification; ONIC network; apply OTP purpose

Revision ID: 69cb5fc8dd8f
Revises: 7205f1a38036
Create Date: 2026-09-25 16:24:17.963983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69cb5fc8dd8f'
down_revision = '7205f1a38036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highest_qualification_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trade_certificate', sa.Enum('none', 'carpenter', 'electrician', 'fitter', 'welder', name='trade_certificate', native_enum=False, create_constraint=True, length=40), nullable=True))
        batch_op.add_column(sa.Column('quota_claim', sa.Enum('open_merit', 'railway_employee_child', 'minority', 'disability', 'ex_serviceman', 'orphan', name='quota_claim', native_enum=False, create_constraint=True, length=40), nullable=True))
        batch_op.add_column(sa.Column('age_relaxation_claim', sa.Enum('none', 'railway_employee_child', 'government_servant', name='age_relaxation_claim', native_enum=False, create_constraint=True, length=40), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_candidate_profiles_highest_qualification_code_qualification_levels'), 'qualification_levels', ['highest_qualification_code'], ['code'])

    # ### end Alembic commands ###

    # Hand-written: autogenerate doesn't see enum value changes. Allow the ONIC network.
    op.drop_constraint(op.f('ck_candidate_accounts_mobile_operator'), 'candidate_accounts', type_='check')
    op.create_check_constraint(
        op.f('ck_candidate_accounts_mobile_operator'),
        'candidate_accounts',
        "mobile_operator IN ('jazz', 'onic', 'telenor', 'ufone', 'zong')",
    )
    # ...and the apply wizard's identity check (OTP purpose "apply").
    op.drop_constraint(op.f('ck_otp_challenges_otp_purpose'), 'otp_challenges', type_='check')
    op.create_check_constraint(
        op.f('ck_otp_challenges_otp_purpose'),
        'otp_challenges',
        "purpose IN ('signup', 'login', 'apply')",
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_candidate_accounts_mobile_operator'), 'candidate_accounts', type_='check')
    op.create_check_constraint(
        op.f('ck_candidate_accounts_mobile_operator'),
        'candidate_accounts',
        "mobile_operator IN ('jazz', 'telenor', 'ufone', 'zong')",
    )
    op.execute("DELETE FROM otp_challenges WHERE purpose = 'apply'")
    op.drop_constraint(op.f('ck_otp_challenges_otp_purpose'), 'otp_challenges', type_='check')
    op.create_check_constraint(
        op.f('ck_otp_challenges_otp_purpose'),
        'otp_challenges',
        "purpose IN ('signup', 'login')",
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_candidate_profiles_highest_qualification_code_qualification_levels'), type_='foreignkey')
        batch_op.drop_column('age_relaxation_claim')
        batch_op.drop_column('quota_claim')
        batch_op.drop_column('trade_certificate')
        batch_op.drop_column('highest_qualification_code')

    # ### end Alembic commands ###
