"""T-028 mobile operator

Revision ID: 7205f1a38036
Revises: 904db39c53bf
Create Date: 2026-09-25 15:55:48.018116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7205f1a38036'
down_revision = '904db39c53bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_operator', sa.Enum('jazz', 'telenor', 'ufone', 'zong', name='mobile_operator', native_enum=False, create_constraint=True, length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_accounts', schema=None) as batch_op:
        batch_op.drop_column('mobile_operator')

    # ### end Alembic commands ###
