"""T-147 job categories

Revision ID: 904db39c53bf
Revises: 4a947c997756
Create Date: 2026-09-25 15:44:31.590947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904db39c53bf'
down_revision = '4a947c997756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_job_categories'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_category_code'), ['category_code'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_jobs_category_code_job_categories'), 'job_categories', ['category_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_category_code_job_categories'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jobs_category_code'))
        batch_op.drop_column('category_code')

    op.drop_table('job_categories')
    # ### end Alembic commands ###
