"""T-148 job gender, eligibility criteria, advertisement file

Revision ID: df563bb5b080
Revises: 421b3b03655d
Create Date: 2026-09-28 10:34:35.780639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df563bb5b080'
down_revision = '421b3b03655d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.Enum('male', 'female', 'transgender', name='job_gender', native_enum=False, create_constraint=True, length=40), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eligibility_criteria', sa.ARRAY(sa.String(length=300)), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column('advertisement_key', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('advertisement_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('advertisement_filename')
        batch_op.drop_column('advertisement_key')
        batch_op.drop_column('eligibility_criteria')

    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
