"""T-063 application fee

Revision ID: e3f45ae9f155
Revises: 69cb5fc8dd8f
Create Date: 2026-09-26 00:42:02.438245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f45ae9f155'
down_revision = '69cb5fc8dd8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('fee_status', sa.Enum('not_required', 'unpaid', 'paid', name='fee_status', native_enum=False, create_constraint=True, length=40), server_default='not_required', nullable=False))
        batch_op.add_column(sa.Column('fee_paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('fee_reference', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('fee_confirmed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_applications_fee_confirmed_by_id_staff_users'), 'staff_users', ['fee_confirmed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_applications_fee_confirmed_by_id_staff_users'), type_='foreignkey')
        batch_op.drop_column('fee_confirmed_by_id')
        batch_op.drop_column('fee_reference')
        batch_op.drop_column('fee_paid_at')
        batch_op.drop_column('fee_status')
        batch_op.drop_column('fee_amount')

    # ### end Alembic commands ###
